colorpicker/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.ColorList.as_view(), name='home'),
    path('updatePattle', views.sendPattle, name='updatePattle')
    # path('', views.ColorList, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('colorpicker.urls')),
]
#  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

colorpicker/models.py
from django.db import models
from django.contrib.auth.models import User

class Color(models.Model):
    title = models.CharField(max_length=200, unique=True)
    color = models.TextField()
    author = models.ForeignKey(User, on_delete= models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

colorpicker/views.py
from django.views import generic
from django.shortcuts import render, redirect, HttpResponse
from .models import Color
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from django.contrib.auth.models import User

# from rest_framework import viewsets, status

@method_decorator(login_required, name='dispatch')
class ColorList(generic.ListView):
    model = Color
    # queryset = Color.objects.filter(author=request.user).order_by('-created_on')
    # queryset = Color.objects.all().order_by('-created_on')
    template_name = 'index.html'

    def get_queryset(self):
        author=self.request.user
        if author is None:
            messages.error(self.request, "User must login")
            return render(self.request,"login.html")
        else:
            return Color.objects.filter(author=self.request.user)

@csrf_protect
def sendPattle(request):
    pass
#     if request.method == 'POST':
#         output = request.POST['updatePattle']
#         # return render(request, "demo.html")
#         return render('demo.html', {'form': c['updatePattle']},  RequestContext(request))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Color Palette</title>

		<link
			href="https://fonts.googleapis.com/css?family=Roboto:400,700"
			rel="stylesheet"
		/>
		<meta name="google" content="notranslate" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link
			rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
			integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
			crossorigin="anonymous"
		/>

		<link rel="stylesheet" href="{% static 'css/lib.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />

	</head>

	<body>
		<!-- Navigation -->
		<nav
			class="navbar navbar-expand-lg navbar-light bg-light shadow"
			id="mainNav"
		>
			<div class="container-fluid">
				<a class="navbar-brand" href="{% url 'home' %}">Color Palette</a>
				<button
					class="navbar-toggler navbar-toggler-right"
					type="button"
					data-toggle="collapse"
					data-target="#navbarResponsive"
					aria-controls="navbarResponsive"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item text-black">
							<a class="nav-link text-black font-weight-bold" href="#">
								About
							</a>
						</li>
						<li class="nav-item text-black">
							<a class="nav-link text-black font-weight-bold" href="#">
								Policy
							</a>
						</li>
						<li class="nav-item text-black">
							<a class="nav-link text-black font-weight-bold" href="#">
								Contact
							</a>
						</li>
						<li class="nav-item text-black">
							<a
								class="nav-link text-black font-weight-bold"
								href="/accounts/logout/"
							>
								Logout
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		{% block content %}
		<!-- Content Goes here -->
		{% endblock content %}

		<!-- Footer -->
		<footer class="py-3 bg-grey">
			<p class="m-0 text-dark text-center">Copyright &copy; Demo</p>
		</footer>
		
		<script src="{% static 'js/script.js' %}"></script>
	</body>
</html>

templates/demo.html
{{request}}

templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
  body {
    font-family: "Roboto", sans-serif;
    font-size: 18px;
    /* background-color: #000; */
    background-color: #fdfdfd;
  }

  .head_text {
    color: white;
  }
  
  .card {
    box-shadow: 0 16px 48px #e3e7eb;
  }
</style>

<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h3 class="site-heading my-4 mt-3 text-white">Color Palette</h3>
          <p class="text-light">Choose Palette</p>
          {% if user.is_authenticated %}
          <div>Hello {{ user.username }}</div>
          {% else %}
          <div>Welcome, please log in</div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8 mt-3 left">
      {% for color in color_list %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">{{ color.title }}</h2>
          <p class="card-text text-muted h6">
            {{ color.author }} | {{ color.created_on }}
          </p>

          <p class="card-text">{{color.color|slice:":200" }}</p>
        </div>
      </div>
      {% endfor %}

      <main>
        <div class="wrap">
          <div class="body">
            <div id="color_picker"></div>
            <p class="sample">
              <i class="sample__color"></i>
              <em class="sample__code"></em>
              <br>
              <form action="updatePattle" method="post">
                {% csrf_token %} 
                <button name="updatePattle" onclick="updatePattle()">Save</button>
              </form>
            </p>
          </div>
          <nav class="controller">
            <label>
              <span>Type: </span>
              <select onchange="onChangeType(this)">
                <option value="default" selected>default</option>
                <option value="circle">circle</option>
                <option value="mini">mini</option>
                <option value="ring">ring</option>
                <option value="none">none</option>
              </select>
            </label>
          </nav>
        </div>
      </main>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>
{% load static %}
<script src="{% static 'js/lib.js' %}"></script>
{%endblock%}

templates/login.html
{% if message %}
<script>
	alert("{{ message }}");
</script>
{% endif %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Sign In</title>
		<style>
			body {
				/* background-image: url(https://images.unsplash.com/photo-1493723843671-1d655e66ac1c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80); */
				background-image: url(https://wallpaperaccess.com/full/410300.jpg);
				/* background-color: #000; */
			}
			input {
				margin-top: 20px;
				height: 30px;
				padding: 12px 20px;
				width: 150px;
				margin: 8px 0;
				border-radius: 5px;
			}
			input[type="submit"] {
				background-color: rgba(7, 179, 185, 0.753);
				color: rgb(255, 255, 255);
				border: none;
				border-radius: 5px;
			}
			button {
				background-color: rgba(7, 179, 185, 0.753);
				color: white;
				width: 150px;
				height: 30px;
				border: none;
				border-radius: 5px;
			}
		</style>
	</head>
	<body>
		<form action="/user/postLogin/" method="post">
			{% csrf_token %}
			<br />
			<!-- Enter Your Email: -->
			<label for="Email">Email</label>
			<input type="email" id="Email" name="email" /><br /><br />
			<!-- Enter Your Password: -->
			<label for="Password">Password</label>
			<input type="password" id="Password" name="pass" /><br /><br />
			<input type="submit" value="SignIn" /><br /><br />
			<!-- <label>
				<input type="checkbox" checked="checked" name="remember" /> Remember
				me
			</label><br /><br /> -->
			<a type="button" href="{% url 'register' %}"> Register </a>
		</form>
	</body>
</html>

templates/sidebar.html
{% block sidebar %}

<style>
  .card {
    box-shadow: 0 16px 48px #e3e7eb;
  }
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right">
  <div class="card my-4">
    <h5 class="card-header">About Us</h5>
    <div class="card-body">
      <p class="card-text">Card-Text</p>
      <a href="#" class="btn btn-danger">Know more!</a>
    </div>
  </div>
</div>

{% endblock sidebar %}